apiVersion: v1
data:
  jwt-secret-key: dGVzdA==
kind: Secret
metadata:
  creationTimestamp: "2026-03-04T11:18:26Z"
  name: app-secrets
  namespace: default
  resourceVersion: "48792"
  uid: 584738f2-d2d5-430d-a7fe-e87e0765b919
type: Opaque
