apiVersion: v1
data:
  apikey: <add-base64-api-key-here>
kind: Secret
metadata:
  creationTimestamp: "2026-03-04T11:33:00Z"
  name: weather
  namespace: default
  resourceVersion: "50524"
  uid: 134620b6-b52c-45bc-ba2e-e1fb3bef3129
type: Opaque
